Small UI improvements
ErikEJ/SqlQueryStress pull request #111
Opened 2021-02-27 09:58 UTC by Tisit

Changed the parameter mapping grid so it requires only one click anywhere in cell to expand the drop down menu. Previously you needed to click twice on arrow or thrice anywhere in the cell. Also made the datatypes appear instantly when choosing anything from the menu.

Changed the query delay field to numeric. Currently it accepts freefrom text. If a text is entered, it crashes on parsing to int. It also fails when left empty (which happened to me).

I hope my description is clear on what has changed.

2021-02-27 16:08 UTC, ErikEJ commented
Clicking on the header on an empty grid crashes the app...

2021-02-27 16:09 UTC, ErikEJ requested changes

2021-02-27 16:09 UTC, ErikEJ commented on src/SQLQueryStress/ParamWindow.cs
> +            if (columnMapGrid.CurrentCell.ColumnIndex == 2)
CurrentCell can be null!

2021-02-27 16:09 UTC, ErikEJ commented on src/SQLQueryStress/ParamWindow.cs
> +            if (columnMapGrid.CurrentCell.ColumnIndex == 2)
CurrentCell can be null!

2021-02-28 08:08 UTC, Tisit commented
I added null checks in both places

2021-02-28 08:11 UTC, merged

2021-02-28 08:11 UTC, ErikEJ commented
Thanks!